 # STRINGS
# string characters ka collection hota hai

name = "Harry"

print(name)

# len function string ki length batata hai
print(len(name))
 # STRING SLICING
# string characters ka collection hota hai

name = "Harry"

print(name)

# len function string ki length batata hai
print(len(name))
 # SKIP SLICING 
 # slicing me step bhi de sakte hai

word = "amazing"

print(word[1:6:2])   # har 2nd character print karega
#        STRING FUNCTIONS 
name = "harry"

# check karta hai string kis word se end ho rahi hai
print(name.endswith("rry"))

# kisi character ki kitni baar repetition hai
print(name.count("r"))

# first letter capital karta hai
print(name.capitalize())

# kisi word ka index batata hai
print(name.find("rr"))

# character replace karta hai
print(name.replace("r", "l"))